<?php
header("Content-type: application/vnd.ms-word");
header("Content-Disposition: attachment;Filename=Analytics_Report_" . date('Y-m-d') . ".doc");
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'Arial', sans-serif; }
        h1 { color: #2c3e50; border-bottom: 2px solid #2c3e50; }
        h2 { color: #18bc9c; margin-top: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .highlight { color: #e74c3c; font-weight: bold; }
    </style>
</head>
<body>
    <h1>Afnan's POS - Analytics Report</h1>
    <p><strong>Date Generated:</strong> <?= date('d/m/Y H:i') ?></p>
    <p><strong>Period:</strong> <?= date('d/m/Y', strtotime($start_date)) ?> to <?= date('d/m/Y', strtotime($end_date)) ?></p>

    <h2>1. Executive Summary</h2>
    <p>This report provides a snapshot of the store's performance over the last 30 days.</p>
    <ul>
        <li><strong>Total Sales:</strong> <?= to_currency($total_sales) ?></li>
        <li><strong>Total Collected:</strong> <?= to_currency($total_payments) ?></li>
        <li><strong>Collection Rate:</strong> <span class="highlight"><?= $collection_rate ?>%</span></li>
        <li><strong>Low Stock Alerts:</strong> <?= $low_inventory_count ?> items need reordering.</li>
    </ul>

    <h2>2. Hot Selling Items (Top 5)</h2>
    <p>The following items are performing exceptionally well:</p>
    <table>
        <thead>
            <tr>
                <th>Item Name</th>
                <th>Category</th>
                <th>Quantity Sold</th>
                <th>Total Revenue</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($hot_items as $item): ?>
            <tr>
                <td><?= esc($item['name']) ?></td>
                <td><?= esc($item['category']) ?></td>
                <td><?= to_quantity_decimals($item['quantity_purchased']) ?></td>
                <td><?= to_currency($item['total']) ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <h2>3. Inventory Health</h2>
    <p>Currently, there are <strong><?= $low_inventory_count ?></strong> items below their reorder level. Please check the Notifications page for details.</p>

    <br><br>
    <hr>
    <p style="text-align: center; font-size: 12px; color: #7f8c8d;">Generated by Afnan's POS</p>
</body>
</html>
